spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1995
    url: jdbc:mysql://localhost:3306/sbms_practice
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082      